project:
  type: website

website:
  title: "LENCERÍA PARA TÚ HOGAR"
  navbar:
    background: white
    left:
      - href: index.qmd
        text: "Inicio"
      - text: "Catálogo"
        menu:
          - href: sabanas.qmd
            text: "Sábanas"
          - href: toallas.qmd
            text: "Toallas"
          - href: toallones.qmd
            text: "Toallones"
          - href: protector.qmd
            text: "Protector de Colchón"
          - href: cortinas.qmd
            text: "Cortinas"
          - href: velos.qmd
            text: "Velos"
          - href: colchasespanolas.qmd
            text: "Colchas Españolas"
          - href: cobijas-piel-conejo.qmd
            text: "Cobijas Piel de Conejo"
          - href: almohadas.qmd
            text: "Almohadas"

format:
  html:
    theme: cosmo
    toc: false
    css: styles.css